projeto_biblioteca/api/urls.py
from django.urls import include, path
from rest_framework import routers

from . import views

app_name = "api"

router = routers.DefaultRouter()
router.register(r"usuarios", views.UserViewSet)
router.register(r"leitores", views.ReaderViewSet)
router.register(r"autores", views.AuthorViewSet)
router.register(r"livros", views.BookViewSet)
router.register(r"exemplares", views.CopyViewSet)
router.register(r"emprestimos", views.BorrowViewSet, basename='emprestimos')
router.register(r"editoras", views.PublisherViewSet)
router.register(r"locais_publicacao", views.PlaceViewSet)
router.register(r"cdds", views.DDCViewSet)
router.register(r"temautor", views.HasAuthorViewSet)

urlpatterns = [
    path("api/", include((router.urls, app_name))),
    path("api/auth", include("rest_framework.urls", namespace="rest_framework"))
]

projeto_biblioteca/biblioteca/urls.py
from django.urls import path

from . import views

app_name = "biblioteca"

urlpatterns = [
    path("", views.inicial, name="inicial"),
    path("livros", views.livros, name="livros"),
    path("livros/<int:livro_id>/", views.detalhes, name="detalhes"),
    path("user/login/", views.login_view, name="login"),
    path("restrito", views.api, name="api"),
]

projeto_biblioteca/projeto_biblioteca/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("biblioteca.urls")),
    path("", include("api.urls")),
    path("admin/", admin.site.urls, name="admin"),
]

projeto_biblioteca/biblioteca/models.py
from datetime import date, datetime, timedelta

from django.db import models


# Função para calcular a data de devolução padrão (hoje + 7 dias)
def get_default_return_date():
    return date.today() + timedelta(days=7)


class Autor(models.Model):
    class Meta:
        verbose_name = "autor"
        verbose_name_plural = "autores"

    def __str__(self):
        return self.nome

    nome = models.CharField(max_length=100)
    codigo_autor = models.CharField(max_length=10, null=True)


class Cdd(models.Model):
    class Meta:
        verbose_name = "CDD"

    def __str__(self):
        return self.nome

    nome = models.CharField(max_length=100)

class Editora(models.Model):
    class Meta:
        verbose_name = "Editora"

    def __str__(self):
        return self.nome

    nome = models.CharField(max_length=100)


class Leitor(models.Model):
    class Meta:
        verbose_name = "leitor"
        verbose_name_plural = "leitores"    
    
    nome = models.CharField(max_length=100)
    ra = models.CharField(max_length=20, unique=True)
    ativo = models.BooleanField(default=True)
    turma = models.CharField(max_length=10, blank=True, null=True)
    def __str__(self):
        return f"{self.nome}"

class Local_Publicacao(models.Model):
    class Meta:
        verbose_name = "Local de Publicação"
        verbose_name_plural = "Locais de Publicação"

    def __str__(self):
        return self.nome

    nome = models.CharField(max_length=100)


class Livro(models.Model):
    class Meta:
        verbose_name = "livro"
        verbose_name_plural = "livros"

    def __str__(self):
        nome = self.titulo
        if self.subtitulo:
            nome+=" : "+self.subtitulo
        return nome

    titulo = models.CharField(max_length=100, verbose_name="Título")
    subtitulo = models.CharField(max_length=100, blank=True)
    ano = models.IntegerField(blank=True, null=True)
    edicao = models.IntegerField(blank=True, null=True, verbose_name="Edição")    
    isbn = models.CharField(max_length=13, blank=True, verbose_name="ISBN")
    iniciais_titulo=models.CharField(max_length=2, verbose_name="Iniciais do Título")
    cdd = models.ForeignKey(Cdd, on_delete=models.SET_NULL, blank=True, null=True, verbose_name="CDD")
    editora = models.ForeignKey(Editora, on_delete=models.SET_NULL, blank=True, null=True)
    local_publicacao = models.ForeignKey(Local_Publicacao, on_delete=models.SET_NULL, blank=True, null=True, verbose_name="Local de Publicação")

class Exemplar(models.Model):
    class Meta:
        verbose_name = "exemplar"
        verbose_name_plural = "exemplares"

    def __str__(self):
        return f"ID {self.id} - Ex. {self.numero_exemplar} - {self.livro.titulo}"

    livro = models.ForeignKey(Livro, on_delete=models.SET_NULL, blank=True, null=True)
    tombo = models.CharField(max_length=45)
    numero_exemplar = models.IntegerField(verbose_name="Número de Exemplar")
    etiqueta_gerada = models.BooleanField()
    baixa = models.BooleanField(default=False)
    motivo_baixa = models.CharField(max_length=250, blank=True, null=True, verbose_name="Motivo da Baixa")
    
    def save(self, *args, **kwargs):       
        if not self.tombo:  # Gera apenas se não existir
            ano_atual = datetime.now().year
            self.tombo = f"Crav.{ano_atual}.{self.id or 'ID_TEMP'}"
        if not self.numero_exemplar:
            ultimo_exemplar = Exemplar.objects.filter(livro=self.livro).order_by('-numero_exemplar').first()
            ultimo_numero = ultimo_exemplar.numero_exemplar if ultimo_exemplar else 0
            self.numero_exemplar = ultimo_numero + 1
        super().save(*args, **kwargs)    
        if 'ID_TEMP' in self.tombo:
            self.tombo = f"Crav.{datetime.now().year}.{self.id}"
            super().save(*args, **kwargs)


class Emprestimo(models.Model):
    class Meta:
        verbose_name = "empréstimo"
        verbose_name_plural = "empréstimos"

    def __str__(self):
        return f"Empréstimo de {self.exemplar.livro.titulo}"

    leitor = models.ForeignKey(Leitor, on_delete=models.SET_NULL, blank=True, null=True)
    exemplar = models.ForeignKey(
       Exemplar, on_delete=models.SET_NULL, blank=True, null=True
    )
    data_emprestimo = models.DateField(default=date.today, verbose_name="Data de Empréstimo")
    data_devolucao = models.DateField(default=get_default_return_date, verbose_name="Data de Devolução")
    devolvido = models.BooleanField(default=False)

class LivroTemAutor(models.Model):
    class Meta:
        verbose_name = "Livro e Autor"
        verbose_name_plural = "Livros e Autores"

    def __str__(self):
        return f"Autor: {self.autor.nome}, Livro: {self.livro.titulo}"

    autor = models.ForeignKey(Autor, on_delete=models.SET_NULL, blank=True, null=True, related_name="livros")
    livro = models.ForeignKey(Livro, on_delete=models.SET_NULL, blank=True, null=True, related_name="autores")

projeto_biblioteca/biblioteca/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from . import models


class UploadCSVLeitores(forms.Form):
    file = forms.FileField()
    
  
        
class ExemplarAdminForm(forms.ModelForm):
    quantidade = forms.IntegerField(
        label="Quantidade de Exemplares",
        required=False,
        min_value=1,
        help_text="Informe a quantidade de exemplares para cadastrar em lote.",
    )

    class Meta:
        model = models.Exemplar
        fields = "__all__"

projeto_biblioteca/biblioteca/views.py
# Create your views here.
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.db.models import Count, Q
from django.shortcuts import get_object_or_404, redirect, render

from . import models


def inicial(request):
    return render(request, "inicial.html", context={"guia_atual": "inicial"})


def livros(request):    
    if request.method == "GET":
        livros = models.Livro.objects.all()        
    else:
        pesquisa = request.POST["termos_pesquisa"]
        livros = models.Livro.objects.filter(Q(titulo__icontains=pesquisa) | Q(isbn__icontains=pesquisa) | Q(autores__autor__nome__icontains=pesquisa))

    context = {"guia_atual": "Livros", "livros": livros}
    return render(request, "livros.html", context)


def detalhes(request, livro_id):
    livro = get_object_or_404(models.Livro, id=livro_id)
    exemplares = models.Exemplar.objects.filter(livro=livro)
    exemplares_disponiveis = (
        exemplares.annotate(
            emprestimos_ativos=Count(
                "emprestimo", filter=Q(emprestimo__devolvido=False)
            )
        )
        .filter(emprestimos_ativos=0)
        .count()
    )
    autores = livro.autores.select_related("autor")
    context = {
        "guia_atual": "Livros",
        "livro": livro,
        "exemplares": exemplares,
        "autores": autores,
        "exemplares_disponiveis": exemplares_disponiveis,
    }
    
    return render(request, "detalhes.html", context)


@login_required(login_url="biblioteca:login")
def api(request):
    # Recuperar a mensagem armazenada na sessão, se houver
    mensagem = request.session.pop('mensagem', None)  
    return redirect("/api")


def login_view(request):
    form = AuthenticationForm(request)

    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            return redirect("/api")
        else:
            messages.error(request, "Login inválido")

    context = {"form": form}
    return render(request, "login.html", context)

projeto_biblioteca/biblioteca/templates/create_user.html
{% extends "index.html" %}
{% block main %}
    <div class="form-wrapper">
        <h1>Cadastrar Usuário</h1>
        {% include "partials/_user-form.html" %}
    </div>
{% endblock main %}

projeto_biblioteca/biblioteca/templates/detalhes.html
<!DOCTYPE html>
{% extends "index.html" %}
{% load static %}
{% block main %}
    <div class="container d-flex flex-column text-center justify-content-center"
         style="padding-top:0px;
                background-color: #fff">
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-12 text-light" style="background:#0d6efd;">
                    <h4 style="margin-bottom: 0px; padding:10px 0 10px 0">{{ livro.titulo }}</h4>
                </div>
                <div class="container-fluid"
                     style="margin-top: 20px;
                            background: #daf1ff;
                            padding: 20px">
                    <p>
                        <strong>Subtítulo:</strong> {{ livro.subtitulo }}
                    </p>
                    <p>
                        <strong>ISBN:</strong> {{ livro.isbn }}
                    </p>
                    <p>
                        <strong>Ano:</strong> {{ livro.ano }}
                    </p>
                    <p>
                        <strong>Edição:</strong> {{ livro.edicao }}
                    </p>
                    <p>
                        <strong>CDD:</strong> {{ livro.cdd.nome }}
                    </p>
                    <p>
                        <strong>Editora:</strong> {{ livro.editora.nome }}
                    </p>
                    <p>
                        <strong>Local de Publicação:</strong> {{ livro.local_publicacao.nome }}
                    </p>
                    <p>
                        <strong>Quantidade de Exemplares:</strong> {{ exemplares.count }}
                    </p>
                    <p>
                        <strong>Exemplares disponíveis:</strong> {{ exemplares_disponiveis }}
                    </p>
                    <p>
                        <strong>Autores:</strong>
                        {% if  livro.autores.all %}
                        {% for autor in livro.autores.all  %}
                        {{autor.autor.codigo_autor}} - {{autor.autor.nome}} 
                            {% if not forloop.last %}
                            ; 
                            {% endif %}
                        {% endfor %}
                        {% else %}
                            Nenhum autor encontrado.
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

projeto_biblioteca/biblioteca/templates/devolucoes.html
<!DOCTYPE html>
{% extends "index.html" %}
{% load static %}
{% block main %}
    <div class="container d-flex flex-column text-center justify-content-center"
         style="padding-top:0px;
                background-color: #fff">
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-12 text-light" style="background:#0d6efd;">
                    <h4 style="margin-bottom: 0px; padding:10px 0 10px 0">Suas Devoluções Pendentes</h4>
                </div>
                <div class="container-fluid"
                     style="overflow-y: auto;
                            height: 600px;
                            background:  #daf1ff;
                            margin-top: 20px">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Livro</th>
                                <th>Data</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for livro in livros %}
                                <tr>
                                    <td>
                                        <a href="{% url 'detalhes_livro' livro.id %}">{{ livro.nome }}</a>
                                    </td>
                                    <td>{{ livro.ano }}</td>
                                    <td>{{ livro.edicao }}</td>
                                    <td>{{ livro.autor }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

projeto_biblioteca/biblioteca/templates/emprestimos.html
<!DOCTYPE html>
{% extends "index.html" %}
{% load static %}
{% block main %}
    <div class="container d-flex flex-column text-center justify-content-center"
         style="padding-top:0px;
                background-color: #fff">
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-12 text-light" style="background:#0d6efd;">
                    <h4 style="margin-bottom: 0px; padding:10px 0 10px 0">Empréstimos</h4>
                </div>
                <div class="container-fluid"
                     style="margin-top: 20px;
                            background: #daf1ff;
                            padding: 20px">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Título do Livro</th>
                                <th>Data de Retirada</th>
                                <th>Data de Devolução</th>
                                <th>Situação</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for emprestimo in emprestimos %}
                                <tr>
                                    <td>{{ emprestimo.exemplar.livro.nome }}</td>
                                    <td>{{ emprestimo.data_emprestimo }}</td>
                                    <td>{{ emprestimo.data_devolucao }}</td>
                                    <td>
                                        {% if emprestimo.devolvido %}
                                            Devolvido
                                        {% else %}
                                            Não Devolvido
                                        {% endif %}
                                    </td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="4">Nenhum empréstimo encontrado.</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

projeto_biblioteca/biblioteca/templates/home.html
<!DOCTYPE html>
{% extends "index.html" %}
{% load static %}
{% block main %}
    <div class="bg-light text-dark py-5">
        <div class="container text-center">
            <img src="{% static '/logo_craveiro.png' %}"
                 class="rounded-circle mb-4"
                 alt="Logo Escola Craveiro"
                 height="200">
            <h1 class="display-4 font-weight-bold">Olá, leitores!</h1>
            <p class="lead">Bem-vindo à biblioteca! Aqui você encontrará a coleção de livros do Craveiro!</p>
            <p class="mt-4">
                <a role="button"
                   class="btn btn-primary btn-lg"
                   href="{% url 'biblioteca:livros' %}">Nossa coleção de livros</a>
            </p>
        </div>
    </div>
    <br>
    <div class="container my-5">
        <div class="row">
            <div class="col-md-6 mb-4">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h2 class="card-title">Por que ler é importante?</h2>
                        <p class="card-text">
                            Ler é bom porque melhora suas habilidades de foco, memória, empatia e comunicação. Também pode reduzir o estresse, melhorar sua saúde mental e ajudar você a viver mais. Ler permite que você aprenda coisas novas que podem auxiliar em ter sucesso no trabalho e relacionamentos.
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 mb-4">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h2 class="card-title">Principais benefícios</h2>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Melhora seu vocabulário e habilidade de compreensão</li>
                            <li class="list-group-item">Reduz o estresse</li>
                            <li class="list-group-item">Melhora a saúde mental</li>
                            <li class="list-group-item">Previne redução cognitiva</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

projeto_biblioteca/biblioteca/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
              crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'global/css/style.css' %}">
        <title>Biblioteca Escolar Digital</title>
        <script src="https://cdn.jsdelivr.net/npm/qrious@4.0.2/build/qrious.min.js"></script>
    </head>
    <body>
        <nav class="navbar bg-body-tertiary fixed-top" style="padding: 0px; margin: 0px">
            <div class="container-fluid justify-content-center align-items-center"
                 style="background-color: #0d6efd">
                <span class="navbar-brand lb-1 h3 text-light">
                    <img src="{% static 'logo_craveiro.png' %}"
                         alt="Logo Escola Craveiro"
                         height="auto"
			 width="100%"
                         style="margin-right: 10px; max-width: 50px">
		    Biblioteca Escolar Digital</span>
            </div>
            <div class="container-fluid justify-content-center align-items-center">
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        {% if guia_atual == 'inicial' %}
                            <a class="nav-link active"
                               aria-current="page"
                               href="{% url 'biblioteca:inicial' %}">Início</a>
                        {% else %}
                            <a class="nav-link"
                               aria-current="page"
                               href="{% url 'biblioteca:inicial' %}">Início</a>
                        {% endif %}
                    </li>
                    <li class="nav-item">
                        {% if guia_atual == 'Livros' %}
                            <a class="nav-link active"
                               aria-current="page"
                               href="{% url 'biblioteca:livros' %}">Livros</a>
                        {% else %}
                            <a class="nav-link"
                               aria-current="page"
                               href="{% url 'biblioteca:livros' %}">Livros</a>
                        {% endif %}
                    </li> 
                    <li class="nav-item">                        
                            <a class="nav-link"
                               aria-current="page"
                               href="/admin">Admin</a>                       
                    </li> 
                    <li class="nav-item">                        
                        <a class="nav-link"
                           aria-current="page"
                           href="{% url 'biblioteca:api' %}">API</a>                       
                </li> 
                </li>
            </ul>
        </div>
    </nav>
    {% block main %}{% endblock %}
    <footer class="bg-primary text-white text-center py-4 fixed-bottom">
        <div class="container">
            <p>&copy; 2025 Site criado para o Projeto Integrador III - UNIVESP.</p>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
            integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
            crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
</body>
</html>

projeto_biblioteca/biblioteca/templates/inicial.html
{% extends "index.html" %}
{% load static %}
{% block main %}
    <div class="container">
        <img src="{% static '/logo_craveiro.png' %}"
             class="rounded float-start"
             alt="Logo Escola Craveiro"
             height="auto"
             width="55%"
             style="margin-right: 20px;
                    margin-top: 15px;
                    max-width: 200px">
        <h1 class="display-4">Olá, leitores!</h1>
        <p>Bem-vindo à biblioteca! Aqui você encontrará a coleção de livros do Craveiro!</p>
        <p style="margin-bottom: 40px;">
            <a role="button" class="btn btn-primary btn-lg" href="/livros"> Nossa coleção de
            livros</a>
        </p>
        <div class="container">
            <div class="row">
                <div class="col">
                    <h1>Por que ler é importante?</h1>
                    <p>
                        Ler é bom porque melhora suas habilidades de foco, memória, empatia e comunicação. Também pode
                        reduzir o estresse, melhorar sua saúde mental e ajudar você a viver mais. Ler também permite
                        você aprender coisas novas que podem auxiliar em ter sucesso no trabalho e relacionamentos.
                    </p>
                </div>
                <div class="col">
                    <h1>Principais benefícios</h1>
                    <ul>
                        <li>Melhora seu vocabulário e habilidade de compreensão</li>
                        <li>Reduz o estresse</li>
                        <li>Melhora a saúde mental</li>
                        <li>Previne redução cognitiva</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

projeto_biblioteca/biblioteca/templates/livros.html
<!DOCTYPE html>
{% extends "index.html" %}
{% load static %}
{% block main %}

    <div class="container d-flex flex-column text-center justify-content-center"
         style="padding-top:0px;
                background-color: #fff">
        <div class="row">
            <p>A pesquisa pode ser feita por título, autor ou ISBN.</p>

            <nav class="navbar bg-body-light">
                <div class="container-fluid justify-content-center align-items-center">
                    <form class="d-flex" role="search" action="/livros" method="POST">
                        {% csrf_token %}
                        <input class="form-control me-2" type="search" placeholder="Pesquisar" aria-label="Pesquisar" name="termos_pesquisa" value={{ termos_pesquisa }}>
                        <button class="btn btn-outline-primary" type="submit">Pesquisar</button>
                    </form>
                </div>
            </nav>
        </div>
        <div class="row" style="margin-top: 20px;">          
            {% if livros|length == 1 %}
                <p>{{ livros|length }} livro encontrado.</p>
            {% elif livros|length > 1 %}
                <p>{{ livros|length }} livros encontrados.</p>
            {% else %}
                <p>Nenhum livro encontrado.</p>
            {% endif %}
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-12 text-light" style="background:#0d6efd;">
                    <h4 style="margin-bottom: 0px; padding:10px 0 10px 0">Nosso Acervo</h4>
                </div>
                <div class="container-fluid"
                     style="overflow-y: auto;
                            height: 600px;
                            background:  #daf1ff;
                            margin-top: 20px">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Título</th>
                                <th>Autor</th>
                                <th>Edição</th>
                                <th>Ano</th>
                                <th>ISBN</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for livro in livros %}
                                <tr>
                                    <td>
                                        <a href="{% url 'biblioteca:detalhes' livro.id %}">{{ livro.titulo }} {% if livro.subtitulo %}: {{livro.subtitulo}}{% endif %}</a>
                                    </td>
                                    <td>
                                    {% for autor in livro.autores.all  %}
                                    {{autor.autor.nome}} 
                                        {% if not forloop.last %}
                                        ; 
                                        {% endif %}
                                    {% endfor %}
                                    </td>
                                    <td>{{ livro.edicao|default_if_none:"" }}</td>
                                    <td>{{ livro.ano|default_if_none:"" }}</td>
                                    <td>{{ livro.isbn|default_if_none:"" }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

projeto_biblioteca/biblioteca/templates/login.html
{% extends "index.html" %}
{% block main %}
    <div class="form-wrapper">
        <h1>Login</h1>
        {% if not user.is_authenticated %}            
            <form action="{{ form_action }}" method="post">
                {% csrf_token %}
                <div class="form-content">
                    {% for field in form %}
                        <div class="form-group">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                            {{ field.errors }}
                            {% if field.help_text %}<p class="help-text">{{ field.help_text }}</p>{% endif %}
                        </div>
                    {% endfor %}
                    {% if form.non_field_errors %}
                        <div class="form-content">
                            <div class="form-group">
                                <div class="message error">{{ form.non_field_errors }}</div>
                            </div>
                        </div>
                    {% endif %}
                </div>
                <div class="form-content">
                    <div class="form-group">
                        <button class="btn" type="submit">Entrar</button>
                        <br>
                    </div>
                </div>
            </form>
        </div>
    {% endif %}
{% endblock main %}

projeto_biblioteca/biblioteca/templates/restrito.html
<!DOCTYPE html>
{% extends "index.html" %}
{% load static %}
{% block main %}


<div class="d-flex flex-column justify-content-center align-items-center">
    <a href="/admin" class="btn btn-primary btn-lg mb-3">Banco de Dados</a>
    <a href="/api" class="btn btn-success btn-lg">API</a>
  </div>
  

{% endblock %}

projeto_biblioteca/biblioteca/templates/user_update.html
{% extends "index.html" %}
{% block main %}
    <div class="form-wrapper">
        <h2>Atualizando Usuário</h2>
        {% include "partials/_user-form.html" %}
        {% if user.is_authenticated %}
            <p class="message">
                Você fez login como {{ user.username }}. Clique <a href="{% url 'biblioteca:logout' %}">aqui</a> para sair.
            </p>
        {% endif %}
    </div>
{% endblock main %}